[project]
name = "langchain-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Victor Hugo", email = "victorhramos.vhr@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "black>=26.10.0",
    "isort>=9.0.2",
    "langchain>=1.4.3",
    "langchain-ollama>=1.1.0",
    "langchain-openai>=1.6.7",
    "python-dotenv>=1.2.4",
]

[project.scripts]
langchain-course = "langchain_course:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
